//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerber_demex.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.ProductRequest = new HashSet<ProductRequest>();
        }
    
        public int Partners_id { get; set; }
        public int PartnerType_id { get; set; }
        public int Director_id { get; set; }
        public int LeagalAdress_id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
        public string Phone { get; set; }
    
        public virtual Directors Directors { get; set; }
        public virtual LegalAdresses LegalAdresses { get; set; }
        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRequest> ProductRequest { get; set; }
    }
}
