//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerber_demex.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRequest
    {
        public int Request_id { get; set; }
        public int Product_id { get; set; }
        public int Partners_id { get; set; }
        public int Count { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
    }
}
